import { Card } from '@/types';

export interface CardPreset {
  name: string;
  bankName: string;
  cardNetwork: Card['cardNetwork'];
  type: Card['type'];
  design: Card['cardDesign'];
  defaultBalance?: number;
  defaultCurrency?: string;
}

export const cardPresets: CardPreset[] = [
  // ========== AMERICAN EXPRESS ==========
  {
    name: 'Amex Gold',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#C9A96E',
      gradientColors: ['#C9A96E', '#B8941D'],
      pattern: 'waves',
      patternColor: 'rgba(0,0,0,0.05)',
      textColor: '#000000',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Platinum',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#E8E8E8',
      gradientColors: ['#E8E8E8', '#D0D0D0'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#000000',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Centurion (Black)',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#1A1A1A',
      gradientColors: ['#1A1A1A', '#0D0D0D'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Blue Cash',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#006FCF',
      gradientColors: ['#006FCF', '#0056A6'],
      pattern: 'dots',
      patternColor: 'rgba(255,255,255,0.1)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Green',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#2E8B57',
      gradientColors: ['#2E8B57', '#1F6B3F'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Rose Gold',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#D4A5A5',
      gradientColors: ['#D4A5A5', '#C48B8B'],
      pattern: 'waves',
      patternColor: 'rgba(0,0,0,0.03)',
      textColor: '#000000',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Delta Gold',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#E31837',
      gradientColors: ['#E31837', '#B8122C'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Hilton Honors',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#104C97',
      gradientColors: ['#104C97', '#0A3A73'],
      pattern: 'dots',
      patternColor: 'rgba(255,255,255,0.08)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Marriott Bonvoy',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#8B4513',
      gradientColors: ['#8B4513', '#6B3410'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Amex Business Platinum',
    bankName: 'American Express',
    cardNetwork: 'amex',
    type: 'credit',
    design: {
      backgroundColor: '#4A4A4A',
      gradientColors: ['#4A4A4A', '#2D2D2D'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },

  // ========== CHASE ==========
  {
    name: 'Chase Sapphire Reserve',
    bankName: 'Chase',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#1A3A5C',
      gradientColors: ['#1A3A5C', '#0D1F33'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Chase Sapphire Preferred',
    bankName: 'Chase',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#1B4F72',
      gradientColors: ['#1B4F72', '#123A54'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Chase Freedom',
    bankName: 'Chase',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#0072CE',
      gradientColors: ['#0072CE', '#005BA3'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Chase Freedom Student',
    bankName: 'Chase',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#00A8E8',
      gradientColors: ['#00A8E8', '#0088C2'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Chase Freedom Unlimited',
    bankName: 'Chase',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#003087',
      gradientColors: ['#003087', '#002060'],
      pattern: 'dots',
      patternColor: 'rgba(255,255,255,0.08)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Chase Ink Business',
    bankName: 'Chase',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#1A1A2E',
      gradientColors: ['#1A1A2E', '#0F0F1A'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },

  // ========== UNITED ==========
  {
    name: 'United MileagePlus Explorer',
    bankName: 'United',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#1B2B4A',
      gradientColors: ['#1B2B4A', '#0F1A2E'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'United Club Infinite',
    bankName: 'United',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#0A1628',
      gradientColors: ['#0A1628', '#050D1A'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },

  // ========== VISA ==========
  {
    name: 'Visa Classic',
    bankName: 'Visa',
    cardNetwork: 'visa',
    type: 'debit',
    design: {
      backgroundColor: '#1A1F71',
      gradientColors: ['#1A1F71', '#0D1040'],
      pattern: 'dots',
      patternColor: 'rgba(255,255,255,0.1)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Visa Infinite',
    bankName: 'Visa',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#000000',
      gradientColors: ['#000000', '#1A1A1A'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.08)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Visa Signature',
    bankName: 'Visa',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#1E3A8A',
      gradientColors: ['#1E3A8A', '#152C6B'],
      pattern: 'circles',
      patternColor: 'rgba(255,255,255,0.06)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Visa Platinum',
    bankName: 'Visa',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#6B7280',
      gradientColors: ['#6B7280', '#4B5563'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },

  // ========== MASTERCARD ==========
  {
    name: 'Mastercard Standard',
    bankName: 'Mastercard',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#EB001B',
      gradientColors: ['#EB001B', '#C40017'],
      pattern: 'circles',
      patternColor: 'rgba(255,255,255,0.1)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Mastercard World Elite',
    bankName: 'Mastercard',
    cardNetwork: 'mastercard',
    type: 'credit',
    design: {
      backgroundColor: '#1A1A1A',
      gradientColors: ['#1A1A1A', '#0D0D0D'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Mastercard Gold',
    bankName: 'Mastercard',
    cardNetwork: 'mastercard',
    type: 'credit',
    design: {
      backgroundColor: '#D4AF37',
      gradientColors: ['#D4AF37', '#B8960C'],
      pattern: 'waves',
      patternColor: 'rgba(0,0,0,0.05)',
      textColor: '#000000',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Mastercard Titanium',
    bankName: 'Mastercard',
    cardNetwork: 'mastercard',
    type: 'credit',
    design: {
      backgroundColor: '#71717A',
      gradientColors: ['#71717A', '#52525B'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },

  // ========== DISCOVER ==========
  {
    name: 'Discover It',
    bankName: 'Discover',
    cardNetwork: 'discover',
    type: 'credit',
    design: {
      backgroundColor: '#FF6000',
      gradientColors: ['#FF6000', '#E65500'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Discover It Miles',
    bankName: 'Discover',
    cardNetwork: 'discover',
    type: 'credit',
    design: {
      backgroundColor: '#1E40AF',
      gradientColors: ['#1E40AF', '#153285'],
      pattern: 'dots',
      patternColor: 'rgba(255,255,255,0.08)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },

  // ========== JCB ==========
  {
    name: 'JCB Platinum',
    bankName: 'JCB',
    cardNetwork: 'jcb',
    type: 'credit',
    design: {
      backgroundColor: '#0066B3',
      gradientColors: ['#0066B3', '#004D8A'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'JPY',
  },
  {
    name: 'JCB Gold',
    bankName: 'JCB',
    cardNetwork: 'jcb',
    type: 'credit',
    design: {
      backgroundColor: '#C9A96E',
      gradientColors: ['#C9A96E', '#B8941D'],
      pattern: 'waves',
      patternColor: 'rgba(0,0,0,0.05)',
      textColor: '#000000',
    },
    defaultBalance: 0,
    defaultCurrency: 'JPY',
  },

  // ========== UNIONPAY ==========
  {
    name: 'UnionPay Diamond',
    bankName: 'UnionPay',
    cardNetwork: 'unionpay',
    type: 'credit',
    design: {
      backgroundColor: '#C41E3A',
      gradientColors: ['#C41E3A', '#9E1830'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'CNY',
  },
  {
    name: 'UnionPay Platinum',
    bankName: 'UnionPay',
    cardNetwork: 'unionpay',
    type: 'credit',
    design: {
      backgroundColor: '#1E3A5F',
      gradientColors: ['#1E3A5F', '#152C48'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'CNY',
  },

  // ========== MIR (Russia) ==========
  {
    name: 'MIR Classic',
    bankName: 'MIR',
    cardNetwork: 'mir',
    type: 'debit',
    design: {
      backgroundColor: '#00A651',
      gradientColors: ['#00A651', '#008542'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },
  {
    name: 'MIR Premium',
    bankName: 'MIR',
    cardNetwork: 'mir',
    type: 'credit',
    design: {
      backgroundColor: '#1A1A2E',
      gradientColors: ['#1A1A2E', '#0F0F1A'],
      pattern: 'dots',
      patternColor: 'rgba(255,255,255,0.06)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },

  // ========== RUSSIAN BANKS ==========
  {
    name: 'Sberbank Gold',
    bankName: 'Sberbank',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#21A038',
      gradientColors: ['#21A038', '#1A802D'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },
  {
    name: 'Sberbank Platinum',
    bankName: 'Sberbank',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#1A1A2E',
      gradientColors: ['#1A1A2E', '#0F0F1A'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },
  {
    name: 'Tinkoff Black',
    bankName: 'Tinkoff',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#333333',
      gradientColors: ['#333333', '#1A1A1A'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },
  {
    name: 'Tinkoff Platinum',
    bankName: 'Tinkoff',
    cardNetwork: 'mastercard',
    type: 'credit',
    design: {
      backgroundColor: '#F2F2F7',
      gradientColors: ['#F2F2F7', '#E5E5EA'],
      pattern: 'dots',
      patternColor: 'rgba(0,0,0,0.05)',
      textColor: '#000000',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },
  {
    name: 'Tinkoff All Airlines',
    bankName: 'Tinkoff',
    cardNetwork: 'mastercard',
    type: 'credit',
    design: {
      backgroundColor: '#1E3A5F',
      gradientColors: ['#1E3A5F', '#152C48'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },
  {
    name: 'VTB Classic',
    bankName: 'VTB',
    cardNetwork: 'visa',
    type: 'debit',
    design: {
      backgroundColor: '#003399',
      gradientColors: ['#003399', '#00297A'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },
  {
    name: 'Alfa-Bank Black',
    bankName: 'Alfa-Bank',
    cardNetwork: 'mastercard',
    type: 'credit',
    design: {
      backgroundColor: '#EF3124',
      gradientColors: ['#EF3124', '#CC2A1F'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },
  {
    name: 'Raiffeisen Gold',
    bankName: 'Raiffeisen',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#D4AF37',
      gradientColors: ['#D4AF37', '#B8960C'],
      pattern: 'waves',
      patternColor: 'rgba(0,0,0,0.05)',
      textColor: '#000000',
    },
    defaultBalance: 0,
    defaultCurrency: 'RUB',
  },

  // ========== KAZAKHSTAN BANKS ==========
  {
    name: 'Kaspi Gold',
    bankName: 'Kaspi Bank',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#F14635',
      gradientColors: ['#F14635', '#D13A2B'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'KZT',
  },
  {
    name: 'Halyk Bonus',
    bankName: 'Halyk Bank',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#0066CC',
      gradientColors: ['#0066CC', '#0052A3'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'KZT',
  },
  {
    name: 'ForteBank',
    bankName: 'ForteBank',
    cardNetwork: 'visa',
    type: 'debit',
    design: {
      backgroundColor: '#00A86B',
      gradientColors: ['#00A86B', '#008755'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'KZT',
  },

  // ========== EUROPEAN BANKS ==========
  {
    name: 'Revolut Standard',
    bankName: 'Revolut',
    cardNetwork: 'visa',
    type: 'debit',
    design: {
      backgroundColor: '#0075EB',
      gradientColors: ['#0075EB', '#005EC2'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'EUR',
  },
  {
    name: 'Revolut Metal',
    bankName: 'Revolut',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#9CA3AF',
      gradientColors: ['#9CA3AF', '#6B7280'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.08)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'EUR',
  },
  {
    name: 'Revolut Ultra',
    bankName: 'Revolut',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#1A1A1A',
      gradientColors: ['#1A1A1A', '#0D0D0D'],
      pattern: 'dots',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'EUR',
  },
  {
    name: 'Wise Card',
    bankName: 'Wise',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#00B9FF',
      gradientColors: ['#00B9FF', '#0094CC'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Monzo Hot Coral',
    bankName: 'Monzo',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#FF4F5E',
      gradientColors: ['#FF4F5E', '#E64554'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'GBP',
  },
  {
    name: 'Monzo Plus',
    bankName: 'Monzo',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#1A3A5F',
      gradientColors: ['#1A3A5F', '#0F2340'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'GBP',
  },
  {
    name: 'N26 Standard',
    bankName: 'N26',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#2D2D2D',
      gradientColors: ['#2D2D2D', '#1A1A1A'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'EUR',
  },
  {
    name: 'N26 Metal',
    bankName: 'N26',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#6B7280',
      gradientColors: ['#6B7280', '#4B5563'],
      pattern: 'lines',
      patternColor: 'rgba(255,255,255,0.08)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'EUR',
  },
  {
    name: 'Starling Bank',
    bankName: 'Starling',
    cardNetwork: 'mastercard',
    type: 'debit',
    design: {
      backgroundColor: '#5B3DF5',
      gradientColors: ['#5B3DF5', '#4528E0'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'GBP',
  },

  // ========== US BANKS ==========
  {
    name: 'Bank of America Cash',
    bankName: 'Bank of America',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#E31837',
      gradientColors: ['#E31837', '#B8122C'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Citi Double Cash',
    bankName: 'Citi',
    cardNetwork: 'mastercard',
    type: 'credit',
    design: {
      backgroundColor: '#003B70',
      gradientColors: ['#003B70', '#002D57'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Capital One Venture',
    bankName: 'Capital One',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#1A3A5F',
      gradientColors: ['#1A3A5F', '#0F2340'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Wells Fargo Active',
    bankName: 'Wells Fargo',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#D71E28',
      gradientColors: ['#D71E28', '#B81820'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'US Bank Altitude',
    bankName: 'US Bank',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#003B5C',
      gradientColors: ['#003B5C', '#002D46'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },

  // ========== ASIAN BANKS ==========
  {
    name: 'DBS Live Fresh',
    bankName: 'DBS',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#FF0000',
      gradientColors: ['#FF0000', '#CC0000'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'SGD',
  },
  {
    name: 'OCBC 365',
    bankName: 'OCBC',
    cardNetwork: 'visa',
    type: 'credit',
    design: {
      backgroundColor: '#E31837',
      gradientColors: ['#E31837', '#B8122C'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'SGD',
  },
  {
    name: 'ICBC Platinum',
    bankName: 'ICBC',
    cardNetwork: 'unionpay',
    type: 'credit',
    design: {
      backgroundColor: '#C41E3A',
      gradientColors: ['#C41E3A', '#9E1830'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'CNY',
  },

  // ========== CRYPTOCARDS ==========
  {
    name: 'Crypto.com Ruby',
    bankName: 'Crypto.com',
    cardNetwork: 'visa',
    type: 'prepaid',
    design: {
      backgroundColor: '#E31837',
      gradientColors: ['#E31837', '#B8122C'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Crypto.com Jade',
    bankName: 'Crypto.com',
    cardNetwork: 'visa',
    type: 'prepaid',
    design: {
      backgroundColor: '#2E8B57',
      gradientColors: ['#2E8B57', '#1F6B3F'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Crypto.com Obsidian',
    bankName: 'Crypto.com',
    cardNetwork: 'visa',
    type: 'prepaid',
    design: {
      backgroundColor: '#1A1A1A',
      gradientColors: ['#1A1A1A', '#0D0D0D'],
      pattern: 'dots',
      patternColor: 'rgba(255,255,255,0.05)',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
  {
    name: 'Binance Card',
    bankName: 'Binance',
    cardNetwork: 'visa',
    type: 'prepaid',
    design: {
      backgroundColor: '#F0B90B',
      gradientColors: ['#F0B90B', '#D4A50A'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#000000',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },

  // ========== CUSTOM ==========
  {
    name: 'Custom Card',
    bankName: 'Custom Bank',
    cardNetwork: 'other',
    type: 'credit',
    design: {
      backgroundColor: '#8E8E93',
      gradientColors: ['#8E8E93', '#636366'],
      pattern: 'none',
      patternColor: 'transparent',
      textColor: '#FFFFFF',
    },
    defaultBalance: 0,
    defaultCurrency: 'USD',
  },
];

export const getPresetByName = (name: string): CardPreset | undefined => {
  return cardPresets.find((preset) => preset.name === name);
};

export const getPresetsByNetwork = (network: string): CardPreset[] => {
  return cardPresets.filter((preset) => preset.cardNetwork === network);
};

export const getPresetsByBank = (bank: string): CardPreset[] => {
  return cardPresets.filter((preset) => 
    preset.bankName.toLowerCase().includes(bank.toLowerCase())
  );
};

export const getPresetsByType = (type: string): CardPreset[] => {
  return cardPresets.filter((preset) => preset.type === type);
};

export const getAllBanks = (): string[] => {
  const banks = new Set(cardPresets.map((p) => p.bankName));
  return Array.from(banks).sort();
};

export const getAllNetworks = (): string[] => {
  const networks = new Set(cardPresets.map((p) => p.cardNetwork));
  return Array.from(networks).sort();
};
